### ISSUE TITLE
Create localkube image

### ISSUE THREAD

**Issue by ethernetdan** [redspread/localkube#15]
I am thinking for the purposes of versioning Kubernetes version the primary distribution of localkube will be a Docker image.

This image should bring up all components involved.

**Comment by rata** [comment]
Probably we can use hyberkube, that is a single binary that runs all the master components and is in upstream kubernetes: https://github.com/kubernetes/kubernetes/tree/master/cmd/hyperkube. This might be the easiest way, as it should be low overhead and supported upstream. There is a docker image for it, as you can see in this docker example[1]. Maybe we can ask if the hyperkube is something that will be supported and is not deprecated or something.

In fact, we may consider using it with vagrant as described here[2]  or do something portable (mac, linux, windows) inspired in this docker example[1].

This guides has just been published, I don't think they were available before.


[1]: http://kubernetes.io/docs/getting-started-guides/docker/
[2]: http://kubernetes.io/docs/getting-started-guides/vagrant/

**Comment by ethernetdan** [comment]
My issues with using hyperkube is it requires that either A) multiple containers be run B) multiple processes within a single container and that the base image is based on debian which adds ~85mb. Considering we are also requiring 2 other images by using weave, I thought we could consolidate a little more.

My current thinking is that we put the `localkube` executable inside the weaveexec image which is based on the minimal alpine linux and has the commands to start weave already inside. I just put in a PR which has a demonstration of this. What do you think?

**Comment by ethernetdan** [comment]
(I am going to merge it because it has some other changes I need but happy to revisit)

**Comment by rata** [comment]
Cool, lgtm! :)
