### ISSUE TITLE
Kube networking

### ISSUE THREAD

**Issue by ethernetdan** [redspread/localkube#7]
One of the requirements of a Kubernetes is that every Pod receive it's own IP address. It seems like the simplest solution to this is to use a software network overlay.

After evaluating several options it looks like [weave](https://github.com/weaveworks/weave) will be the simplest way to fulfill this requirement. It should be able to implemented in a couple hours and should be reasonable to work with to support multiple nodes in the future.

It operates by proxying requests to the Docker daemon allowing it to correctly configure the networking any containers created.

**Comment by rata** [comment]
Just curious, why are you thinking about multiple nodes support in the future? I thought local dev (with localkube) and then connect to a another kubernetes cluster is the common use case.

**Comment by ethernetdan** [comment]
@rata: There are certain things that would be hard to develop without having a multi-Node cluster, for example a custom Kubernetes scheduler (determines which Pods go on which Nodes). This is definitely would be down the road, the primary focus now is providing a single Node cluster for development.

**Comment by rata** [comment]
@ethernetdan: Oh, I haven't thought of that. Not sure if it will be needed, but it might. It seems like a good solution if it's easy and allows this, then :)
