### ISSUE TITLE
Cluster DNS

### ISSUE THREAD

**Issue by ethernetdan** [redspread/localkube#8]
Kubernetes requires DNS to be run in order to resolve requests to services.

This could be implemented by running the [SkyDNS](https://github.com/skynetservices/skydns) server and [kube2sky](https://github.com/kubernetes/kubernetes/tree/a3c00aa/cluster/addons/dns/kube2sky).

These components could be run either as part of the localkube executable or with an [RC](https://github.com/kubernetes/kubernetes/blob/d644062/cluster/addons/dns/skydns-rc.yaml.in) and [Service](https://github.com/kubernetes/kubernetes/blob/d644062/cluster/addons/dns/skydns-svc.yaml.in).

**Comment by rata** [comment]
Isn't it possible that running it as a go routine can be a problem in the future, if they change the way it's launched or it's not so easy to d it as a go routine? Or it's not possible that using a go routine can cause a problem?

Also, running it with an RC and Service, isn't just as trivial as using the add-on scripts on kubernetes repo? (as we will already have a kubernetes running and all things necessary to run the scripts, IIUC)

**Comment by ethernetdan** [comment]
Compiling localkube with these dependencies definitely runs the risk of breaking changes in the future. Using Godeps (which needs to be added to this repo) allows us to at least guarantee a working build but the drawbacks of potential breaking changes are making my lean towards using RC/Service.

Yup, it would be that easy! I'm thinking that we include it as part of localkube because I would think DNS is essential for the vast majority of Kubernetes users. Thoughts?

**Comment by rata** [comment]
On Mon, Mar 14, 2016 at 04:56:32PM -0700, Dan Gillespie wrote:
> Compiling localkube with these dependencies definitely runs the risk of
> breaking changes in the future. Using Godeps (which needs to be added to this
> repo) allows us to at least guarantee a working build but the drawbacks of
> potential breaking changes are making my lean towards using RC/Service.

Yeah, me too.

> 
> Yup, it would be that easy! I'm thinking that we include it as part of
> localkube because I would think DNS is essential for the vast majority of
> Kubernetes users. Thoughts?

Yes, DNS is every time more important and I think it will be mandatory since
kubernetes 1.2 due this week, so I think it's essential :)



Thanks a lot,
Rodrigo

**Comment by ethernetdan** [comment]
It looks like skydns should be able to be integrated in the binary. Unfortunately kube2sky does not export any methods that we can call so it will have to be shipped as it's own executable.

Also the setup requires etcd which is already being compiled against.

**Comment by ethernetdan** [comment]
A service can be used to expose DNS to the cluster
